@echo off
echo Starting Clinova Full Stack...

echo Starting Backend...
start "Clinova Backend" cmd /k "cd backend && npm run dev"

echo Starting Frontend...
start "Clinova Frontend" cmd /k "cd frontend && npm run dev"

echo Starting AI Service...
start "Clinova AI Service" cmd /k "cd ai_service && call venv\Scripts\activate.bat && python app.py"

echo All services are starting up in new windows!
