import React, { useEffect, useState } from 'react';
import { AlertCircle } from 'lucide-react';
import RiskMap from '../map/RiskMap';
import AnalyticsSummary from '../analytics/AnalyticsSummary';
import { predictionService } from '../../services/prediction.service';
import type { PredictionReportDoc } from '../../models/prediction.model';

export default function DashboardContainer() {
  const [latestPrediction, setLatestPrediction] = useState<PredictionReportDoc | null>(null);
  const [predictionHistory, setPredictionHistory] = useState<PredictionReportDoc[]>([]);
  const [cityPredictions, setCityPredictions] = useState<{ [cityName: string]: PredictionReportDoc }>({});
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Function to load predictions from database/API
  const loadData = async () => {
    setLoading(true);
    setError(null);
    try {
      // Get latest saved prediction
      const latest = await predictionService.getLatestPrediction();
      setLatestPrediction(latest);

      // Get last 7 predictions for history chart
      const history = await predictionService.getPredictionHistory(7);
      setPredictionHistory(history);

      // Group predictions by city
      const allReports = await predictionService.getReports();
      const cityMap: { [cityName: string]: PredictionReportDoc } = {};
      allReports.forEach(report => {
        if (!cityMap[report.city]) {
          cityMap[report.city] = report;
        }
      });
      setCityPredictions(cityMap);
    } catch (err: any) {
      console.error('Error fetching prediction reports:', err);
      setError('Could not connect to the API. Please ensure the backend server is running.');
    } finally {
      setLoading(false);
    }
  };

  // Initial load
  useEffect(() => {
    loadData();

    // Auto-update map if a new prediction is saved/generated by listening to custom events
    const handlePredictionUpdate = () => {
      loadData();
    };

    window.addEventListener('clinova-prediction-saved', handlePredictionUpdate);
    return () => {
      window.removeEventListener('clinova-prediction-saved', handlePredictionUpdate);
    };
  }, []);

  return (
    <div style={styles.dashboardSection}>
      <h2 style={styles.sectionHeader}>Colombo District Dengue Risk Dashboard</h2>
      
      {error && (
        <div style={styles.errorBanner}>
          <AlertCircle size={20} color="#ef4444" />
          <div style={styles.errorDetails}>
            <span style={styles.errorText}>{error}</span>
            <button onClick={loadData} style={styles.retryBtn}>Retry Connection</button>
          </div>
        </div>
      )}

      <div style={styles.containerGrid}>
        {/* Map Panel */}
        <div style={styles.mapPanel}>
          <RiskMap 
            prediction={latestPrediction} 
            cityPredictions={cityPredictions} 
            loading={loading} 
          />
        </div>

        {/* Analytics Details Side Panel */}
        <div style={styles.analyticsPanel}>
          <AnalyticsSummary 
            prediction={latestPrediction} 
            history={predictionHistory}
            onRefresh={loadData}
            loading={loading}
          />
        </div>
      </div>
    </div>
  );
}

const styles: { [key: string]: React.CSSProperties } = {
  dashboardSection: {
    marginTop: '40px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    maxWidth: '1400px',
    margin: '40px auto 0 auto',
    padding: '0 40px',
  },
  sectionHeader: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#ffffff',
    margin: 0,
  },
  errorBanner: {
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    border: '1px solid rgba(239, 68, 68, 0.25)',
    borderRadius: '12px',
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  errorDetails: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  errorText: {
    fontSize: '13.5px',
    color: '#f87171',
    fontWeight: '500',
  },
  retryBtn: {
    backgroundColor: '#ef4444',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    padding: '6px 14px',
    fontSize: '12px',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(239, 68, 68, 0.3)',
    transition: 'all 0.2s',
  },
  containerGrid: {
    display: 'grid',
    gridTemplateColumns: '1.6fr 1fr',
    gap: '24px',
  },
  mapPanel: {
    minHeight: '500px',
  },
  analyticsPanel: {},
};

// CSS media query overrides for responsive dashboard grid layouts
if (typeof window !== 'undefined') {
  const styleEl = document.createElement('style');
  styleEl.innerHTML = `
    @media (max-width: 1024px) {
      div[style*="display: grid; grid-template-columns: 1.6fr 1fr"] {
        grid-template-columns: 1fr !important;
      }
    }
  `;
  document.head.appendChild(styleEl);
}
